# Generated by Django 5.0.6 on 2024-07-31 17:24

from django.db import migrations, models


class Migration(migrations.Migration):

    dependencies = [
        ('plants', '0001_initial'),
    ]

    operations = [
        migrations.CreateModel(
            name='Plant',
            fields=[
                ('id', models.BigAutoField(auto_created=True, primary_key=True, serialize=False, verbose_name='ID')),
                ('scientific_name', models.CharField(max_length=255)),
                ('local_name', models.CharField(max_length=255)),
                ('medicinal_benefits', models.TextField()),
            ],
        ),
    ]
