# Generated by Django 5.0.6 on 2024-07-31 17:54

import django.db.models.deletion
from django.db import migrations, models


class Migration(migrations.Migration):

    dependencies = [
        ('plants', '0003_plantimage_plant'),
    ]

    operations = [
        migrations.AlterField(
            model_name='plantimage',
            name='plant',
            field=models.ForeignKey(on_delete=django.db.models.deletion.CASCADE, related_name='images', to='plants.plant'),
        ),
    ]
