# Generated by Django 5.0.6 on 2024-07-31 18:17

from django.db import migrations


class Migration(migrations.Migration):

    dependencies = [
        ('plants', '0004_alter_plantimage_plant'),
    ]

    operations = [
        migrations.RemoveField(
            model_name='plantimage',
            name='plant',
        ),
    ]
